language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

before_deploy: "echo 'ready?'"

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "ca-central-1"
  app: "elastic-beanstalk-tutorial"
  env: "elastic-beanstalk-tutorial-dev"
  bucket_name: "elasticbeanstalk-ca-central-1-882371129764"
  on:
    branch: master

after_deploy:
  - echo "done deploying"
