version: "3"

services:
  node-server:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb+srv://jotarokujo7:standproud@cluster0-lrzjn.mongodb.net/test?retryWrites=true&w=majority"
